# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/hdmi_disp.xci
# IP: The module: 'hdmi_disp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/hdmi_disp.xci
# IP: The module: 'hdmi_disp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/lab_work/4k/HDMI_Output_Disp/HDMI_Output_Disp.srcs/sources_1/ip/hdmi_disp/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
